# Usa a imagem oficial e leve do Python
FROM python:3.11-slim

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Copia o arquivo de dependências para dentro do container
COPY requirements.txt .

# Instala as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o resto do código do Gleidson para dentro do container
COPY . .

# Expõe a porta padrão que o Streamlit usa (8501)
EXPOSE 8501

# Comando para rodar a aplicação web quando o container iniciar
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]